---
- name: Gather facts.
  ios_facts:
    gather_subset: "!all"
  tags: facts
- name: output
  ios_command:
    commands: "dir flash:"
  register: dir

- name: Set variables.
  set_fact:
    is_on_correct:              "{{ansible_net_image == 'flash:' + ios_version}}"
    is_on_flash:                "{{dir.stdout[0] | regex_search(ios_version) | ternary('yes','no')}}"
    free_space:                 "{{dir.stdout[0] | regex_search(ios_freespace_regex)}}"
    is_pkg_version_upgraded:    "{{dir.stdout[0] | regex_search(ios_pkg_version) | ternary('yes','no')}}"

- name: Update IOS.
  block:
    - name: Copy file.
      ios_command:
        commands:
          - command: copy ftp://cisco:Tran$f3rD8ta@10.217.25.197/{{ios_version}} flash://{{ios_version}}
            prompt: 'Destination filename [{{ios_version}}]?'
            answer: "\r"
        wait_for: result[0] contains OK
  when: (not is_on_flash) and (not is_on_correct) and (free_space | int) > (ios_filesize | int)

- name: Calculate chksum.
  ios_command:
    commands: verify /md5 flash:{{ios_version}}
  register: md5
  tags: md5

- name: Check md5
  fail:
    msg:
      - "The MD5 checksums do not match"
      - "File check sum is                :{{ios_version_chksum}}"
      - "The device calculated checksum is:{{md5.stdout[0] | regex_search( '[\\d|\\w]{32}' ) }}"
  when: not md5.stdout[0] | regex_search(ios_version_chksum)
  tags: md5

- name: Change Boot
  ios_command:
    commands:
      # - command: dir
      - command: request platform software package install switch all file flash:{{ios_version}} auto-copy
    wait_for: result[0] contains {{ios_boot_response}}
  when: (not is_pkg_version_upgraded) and (ansible_net_image == "flash:packages.conf")
  tags: boot
