---
- name: Gather facts.
  ios_facts:
    gather_subset: "!all"
  tags: facts

# - name: Models
#   debug:
#     msg: "In stack {{item}}"
#   loop: "{{ansible_net_stacked_models}}"

# - name: Set Up Default Interface Configuration
#   ios_interface:
#       aggregate: "{{interfaces_UXM}}"
#       # aggregate:
#       #   - { name: twoGigabitEthernet1/0/2}
#       #   - { name: twoGigabitEthernet1/0/2}

#       # name: twoGigabitEthernet {{my_idx+1}}/0/2
#       description: NewTest
#       state: present
#       enabled: False
  # loop: "{{ansible_net_stacked_models}}"
  # loop_control:
  #   index_var: my_idx
  # - name: Create Staging Directory
  #   file:
  #     path: ./staging
  #     state: directory

  # - name: Create Interfaces
  #   template: 
  #     src: generate_interfaces.j2
  #     dest: ./staging/output
      
# - name: Print Dict
#   debug:
#     msg:  "Interface {{item.0.type}}  {{item.1}}"
#   loop:  "{{ version|subelements('interfaces') }}"
# - name: Print Dict
#   debug:
#     msg:  "Model {{item.0.type}}  Interface {{item.1.name}} begins {{item.1.start}} ends {{item.1.end}}"
#   loop:  "{{ version|subelements('interfaces') }}"

  # - name: Create Interfaces
  #   template: 
  #     src: generate_interfaces.j2
  #     dest: ./roles/base_config/vars/output

# - name: Set up 
#   set_fact:
#     interfaces: one
# - debug: 
#     msg: "{{interfaces}}"

